---
title: "Leisure Activities - Meths & Stats"
shorttitle: "meths & stats"
author:
  - name: Melissa Schneiderová
    corresponding: true
    affiliations:
      - name: PVSPS
        department: OVV
        city: Prague
  - name: Josef Mana
    corresponding: false
    affiliations:
      - name: PVSPS
        department: OVV
        city: Prague
  - name: Hana Georgi
    corresponding: true
    affiliations:
      - name: PVSPS
        department: OVV
        city: Prague
abstract: ""
keywords: [cool Bayes stats]
author-note:
  disclosures:
    conflict of interest: The authors has no conflict of interest to declare.
format:
  apaquarto-pdf: default
bibliography: references.bib
---

# Methods

## Statistical analyses

### VLS-ALQ

The dimensionality of the VLS-ALQ questionnaire scale in our sample was first checked via the confirmatory factor analysis (CFA) as implemented in the *lavaan* R package [@lavaan; @rsoft]. A three-factor model with separate 'Private,' 'Public,' and 'Religiious' independent dimensions, a second order factor model with separate 'Private,' 'Public,' and 'Religiious' and a superordinate 'Social' factor, and separate unidimensional models for the 'Private' and the 'Public' subscales. Models were evaluated by Tucker Lewis Index (TLI), Comparative Fit Index (CFI) and root-mean-square-error-aproximation (RMSEA) with values of TLI > .9, CFI > .9, and RMSEA < .08 considered indicating adequate fit. Next, internal consistency of the full questionnaire and the 'Public' and the 'Private' subscales were estimated via the Cronbach's $\alpha$ and Guttman's Lambda 6 (G6). Internal consistency indexes were estimated in the *psych* R package using the default settings [@psych; @rsoft]. Following the classical recommendations for interpretation of coefficient $\alpha$ [@streiner2003; @nunnally1994], we consider values above 0.7 as sufficient for early research, values above 0.8 as sufficient for basic research, and values above 0.9 as necessary for clinical use.

Sum scores of the full VLS-ALQ questionnaire as well as its 'Private' and 'Public' subscales were descibed by their in-sample means $\pm$ standard deviations for SA and non-SA groups separately. The null hypothesis that SA and non-SA groups' means are equal was tested via the independent sample *t*-test with Welch modification to the degrees of freedom and effect size of mean differences characterised by Cohen's d. The null hypothesis that regarding test scores in SA and non-SA groups, neither distribution is stochastically greater than the other, was tested via the Mann-Whitney U test with effect size characterised by Vargha and Delaney A as implemented in the *effsize* R package [@effsize; @vargha2000]. Decision threshold for claiming statistically significant deviance from a null hypothesis in these comparisons was set at p < .05.



### COBRA-A

### Leisure activities

# Results

# Appendix
